issue-06/initial commit
the-coding-force/exploring-kotlin-coroutines__backend__spring-kotlin__poc pull request #11
Opened 2024-10-05 10:48 UTC by Adriano-Santtos

2024-10-05 10:53 UTC, Adriano-Santtos commented on src/main/resources/application.yaml
> +    url: jdbc:postgresql://localhost:5432/task-manager-poc
wrong name

2024-10-06 16:50 UTC, joseiedo requested changes

2024-10-06 16:50 UTC, joseiedo commented on docker-compose.yml
> +    networks:
```suggestion
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
```

Faltou corrigir o path aqui pro grafana subir já configurado. Também dá pra mover tudo que tá na pasta docker pra raiz. Tu que sabe!

2024-10-06 20:07 UTC, Adriano-Santtos commented on docker-compose.yml
> +    networks:
Boa mestre, vou mover tudo para dentro de docker
Movi para fora para fazer um teste e esqueci de mover novamente

2024-10-07 03:09 UTC, joseiedo approved these changes

2024-10-07 03:26 UTC, merged

2024-10-07 03:35 UTC, Lucass-trra reviewed
Código bem estruturado, a ideia dos scripts SQL foi interessante para que ja tenha um esquema de tabela definido para que já se possa popular os primeiros dados, sem erros vigentes.